apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: catalog-spc
  namespace: catalog
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "$EKS_CLUSTER_NAME/catalog-secret"
          objectType: "secretsmanager"
          jmesPath:
            - path: username
              objectAlias: username
            - path: password
              objectAlias: password
  secretObjects:                
    - secretName: catalog-secret
      type: Opaque
      data:
        - objectName: username
          key: username
        - objectName: password
          key: password