apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- fsxn-secret.yaml
- fsxn-backend-nas.yaml

configMapGenerator:
- name: fsxnconfig
  envs: 
  - config.env

generatorOptions:
  disableNameSuffixHash: true

vars:
- name: FSXN_IP
  objref:
    kind: ConfigMap
    name: fsxnconfig
    apiVersion: v1
  fieldref:
    fieldpath: data.FSXN_IP
- name: FSXN_ADMIN_PASSWORD
  objref:
    kind: ConfigMap
    name: fsxnconfig
    apiVersion: v1
  fieldref:
    fieldpath: data.FSXN_ADMIN_PASSWORD
configurations:
  - env-var-transformer.yaml